### ISSUE TITLE
smartctl can't see my disks

### ISSUE THREAD

**Issue by walmins** [modem7/telegraf#8]
Hello,
I try to use your example to run telegraf in docker for synology, but `smartctl --scan` can't see my disks.

Do you have any idea?
in my `docker-compose.yml` file
```
      - /:/hostfs:ro
```
in my `telegraf.env`
```
HOST_ETC=/hostfs/etc
HOST_PROC=/hostfs/proc
HOST_SYS=/hostfs/sys
HOST_VAR=/hostfs/var
HOST_RUN=/hostfs/run
HOST_MOUNT_PREFIX=/hostfs
```

**Comment by modem7** [comment]
Well, my readme is garbage isn't it?

Apologies for that!

Try adding privileged rights to the container.

I'll investigate further (currently on my phone) when I'm back at the pc.

**Comment by modem7** [comment]
@walmins  For the compose file, please try this:

```
  # Telegraf - Open source server agent
  telegraf:
    # image: telegraf:alpine
    image: modem7/telegraf
    container_name: Telegraf
    hostname: Telegraf
    privileged: true
    user: telegraf:$PGID
    networks:
      - isonet
      - isolated
    # network_mode: "host"
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_ETC=/hostfs/etc
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs #changed
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    # labels: 
    #   - backup
    volumes:
      - $USERDIR/TIGVStack/Telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/hda/files/drives:/hostfs/var/hda/files/drives:ro
      - /run/udev:/run/udev:ro #changed
      - /:/hostfs:ro
    depends_on:
      - influxdb
    restart: always
```
